# Generated by Django 5.1.4 on 2025-01-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weprovideheader_weprovideitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeProvideItems',
            new_name='WeProvideItem',
        ),
    ]
