# Generated by Django 5.1.4 on 2025-01-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_serviceheader_delete_weprovideheader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceheader',
            old_name='name',
            new_name='title',
        ),
    ]
