# Generated by Django 5.1.4 on 2025-01-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_specialitiesheader_rename_weprovideitem_specialities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialities',
            name='image',
        ),
        migrations.AddField(
            model_name='specialities',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='services/'),
        ),
    ]
