# Generated by Django 5.1.4 on 2025-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_specialities_image_specialities_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('airflow_type', models.CharField(max_length=255)),
                ('filtration_efficiency', models.CharField(max_length=255)),
                ('noise_level', models.CharField(max_length=255)),
                ('compliance', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='equipment_images/')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
