# Generated by Django 5.1.4 on 2025-01-11 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='airflow_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='compliance',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='filtration_efficiency',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='noise_level',
        ),
        migrations.CreateModel(
            name='EquipmentSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=255)),
                ('spec_value', models.CharField(max_length=255)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='core.equipment')),
            ],
        ),
    ]
