# Generated by Django 5.1.4 on 2025-01-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_equipment_airflow_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialities',
            new_name='Speciality',
        ),
        migrations.AlterModelOptions(
            name='abouthero',
            options={'verbose_name': 'About Us Hero Section', 'verbose_name_plural': 'About Us Hero Sections'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='consultant',
            options={'verbose_name': 'Consultant', 'verbose_name_plural': 'Consultants'},
        ),
        migrations.AlterModelOptions(
            name='consultantheader',
            options={'verbose_name': 'Consultant Header', 'verbose_name_plural': 'Consultant Headers'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipments'},
        ),
        migrations.AlterModelOptions(
            name='equipmentspec',
            options={'verbose_name': 'Equipment Specification', 'verbose_name_plural': 'Equipment Specifications'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='serviceheader',
            options={'verbose_name': 'Service Header', 'verbose_name_plural': 'Service Headers'},
        ),
        migrations.AlterModelOptions(
            name='specialitiesheader',
            options={'verbose_name': 'Specialities Header', 'verbose_name_plural': 'Specialities Headers'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Speciality', 'verbose_name_plural': 'Specialities'},
        ),
    ]
