# Generated by Django 5.1.4 on 2025-01-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_testimonial_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultantHeader',
            new_name='HomeAboutHero',
        ),
        migrations.RenameModel(
            old_name='SpecialitiesHeader',
            new_name='HomeConsultantHeader',
        ),
        migrations.RenameModel(
            old_name='ServiceHeader',
            new_name='HomeServiceHeader',
        ),
        migrations.RenameModel(
            old_name='AboutHero',
            new_name='HomeSpecialitiesHeader',
        ),
        migrations.AlterModelOptions(
            name='homeabouthero',
            options={'verbose_name': 'About Us Hero Section', 'verbose_name_plural': 'About Us Hero Sections'},
        ),
        migrations.AlterModelOptions(
            name='homeconsultantheader',
            options={'verbose_name': 'Consultant Header', 'verbose_name_plural': 'Consultant Headers'},
        ),
        migrations.AlterModelOptions(
            name='homespecialitiesheader',
            options={'verbose_name': 'Specialities Header', 'verbose_name_plural': 'Specialities Headers'},
        ),
    ]
