# Generated by Django 5.1.4 on 2025-01-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_consultantheader_homeabouthero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialitiesHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_title', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('specialties_count', models.CharField(blank=True, max_length=100, null=True)),
                ('surgeries', models.CharField(blank=True, max_length=100, null=True)),
                ('years_exp_count', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='specialities_hero')),
                ('image_badge_one', models.CharField(blank=True, max_length=100, null=True)),
                ('image_badge_two', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Specialities Hero',
                'verbose_name_plural': 'Specialities Heros',
            },
        ),
        migrations.CreateModel(
            name='SpecialitiesMainHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specialities Main Header',
                'verbose_name_plural': 'Specialities Main Headers',
            },
        ),
    ]
