# Generated by Django 5.1.4 on 2025-01-12 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_specialitieshero_specialitiesmainheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialitieshero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialitieshero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
