# Generated by Django 5.1.4 on 2025-01-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_specialitieshero_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeabouthero',
            options={'verbose_name': 'Home About Us Hero Section', 'verbose_name_plural': 'Home About Us Hero Sections'},
        ),
        migrations.AlterModelOptions(
            name='homeconsultantheader',
            options={'verbose_name': 'Home Consultant Header', 'verbose_name_plural': 'Home Consultant Headers'},
        ),
        migrations.AlterModelOptions(
            name='homeserviceheader',
            options={'verbose_name': 'Home Service Header', 'verbose_name_plural': 'Home Service Headers'},
        ),
        migrations.AlterModelOptions(
            name='homespecialitiesheader',
            options={'verbose_name': 'Home Specialities Header', 'verbose_name_plural': 'Home Specialities Headers'},
        ),
    ]
