# Generated by Django 5.1.4 on 2025-01-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_homeabouthero_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialitieshero',
            old_name='surgeries',
            new_name='surgeries_count',
        ),
    ]
