# Generated by Django 5.1.4 on 2025-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_surgeries_specialitieshero_surgeries_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='benefits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='stat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
