# Generated by Django 5.1.4 on 2025-01-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_speciality_about_speciality_benefits_speciality_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantsMainHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('mini_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultants Main Header',
                'verbose_name_plural': 'Consultants Main Headers',
            },
        ),
    ]
