# Generated by Django 5.1.4 on 2025-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_aboutachievements_aboutcontactdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='mission',
            name='list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vision',
            name='list',
            field=models.JSONField(default=list),
        ),
    ]
