# Generated by Django 5.1.4 on 2025-01-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_category_blog_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescCarousal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='desc-carousal')),
            ],
        ),
        migrations.CreateModel(
            name='MobCarousal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='mob-carousal')),
            ],
        ),
    ]
