# Generated by Django 5.1.4 on 2025-01-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_blog_categories_alter_mission_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantsmainheader',
            name='mini_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
