# Generated by Django 5.1.4 on 2025-01-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_consultantsmainheader_mini_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desccarousal',
            name='image',
            field=models.FileField(upload_to='desc-carousal/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to='equipment/'),
        ),
        migrations.AlterField(
            model_name='mobcarousal',
            name='image',
            field=models.FileField(upload_to='mob-carousal/'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='speciality/'),
        ),
    ]
