# Generated by Django 5.1.4 on 2025-03-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_desccarousal_image_alter_equipment_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.EmailField(blank=True, max_length=225, null=True)),
                ('phone', models.CharField(blank=True, max_length=225, null=True)),
                ('age', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('preferred_date', models.CharField(blank=True, max_length=225, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=225, null=True)),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consultant')),
            ],
        ),
    ]
