# Generated by Django 5.1.4 on 2025-03-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_speciality_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CTASection',
        ),
        migrations.DeleteModel(
            name='OurValues',
        ),
        migrations.AlterModelOptions(
            name='vision',
            options={'verbose_name': 'Vission', 'verbose_name_plural': 'Vissions'},
        ),
    ]
