# Generated by Django 5.1.4 on 2025-03-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_ctabutton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutAchievements',
        ),
        migrations.DeleteModel(
            name='AboutContactDetails',
        ),
        migrations.DeleteModel(
            name='AboutCoreValues',
        ),
        migrations.DeleteModel(
            name='AboutFeatures',
        ),
        migrations.DeleteModel(
            name='AboutStats',
        ),
    ]
