# Generated by Django 5.1.4 on 2025-03-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_inquiry_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeabouthero',
            name='feature_one_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabouthero',
            name='feature_one_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabouthero',
            name='feature_two_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabouthero',
            name='feature_two_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabouthero',
            name='mini_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
