# Generated by Django 5.1.7 on 2025-03-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_homeabouthero_feature_one_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='category',
            field=models.CharField(blank=True, choices=[('Surgical Procedures', 'Surgical Procedures'), ('Endoscopic Surgery', 'Endoscopic Surgery')], max_length=255, null=True),
        ),
    ]
