# Generated by Django 5.1.7 on 2025-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_speciality_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
